language: python
python:
  - "3.9"
install:
  - cd api_consulta
  - pipenv install --dev
  - pipenv run ./manage.py migrate
  - cd ..
  - cd api_cotacao
  - pipenv install --dev
  - pipenv run ./manage.py migrate
script:
  - pipenv run python manage.py test
  - cd ..
  - cd api_consulta
  - pipenv run python manage.py test
