language: python
python:
  - "3.9"
install:
  - cd api_consulta
  - pipenv install --dev
  - pipenv run ./manage.py migrate
  - mkdir staticfiles
  - cd ..
  - cd api_calculo
  - pipenv install --dev
  - pipenv run ./manage.py migrate
  - mkdir staticfile
script:
  - pipenv run manage.py test
  - cd ..
  - cd api_consulta
  - pipenv run manage.py test
