version: '3.7'

services:

  api-cotacao:
    container_name: api-cotacao
    build:
      context: .
      dockerfile: ../Dockerfile
    command: pipenv run gunicorn settings.wsgi --bind 0:9010
    env_file: .env
    ports:
      - 9010:9010
    image: api-cotacao:1.0.0
    restart: on-failure
    volumes:
      - .:/app

networks:
  default:
    name: caddy-proxy
    external: true
