version: '3.7'

services:

  api:
    container_name: api-imobiliaria
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run gunicorn imobiliaria.wsgi --bind 0.0.0.0:9001
    env_file: .env
    image: api_imobiliaria
    restart: on-failure
    volumes:
    - .:/app

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python manage.py migrate
    env_file: .env
    image: api_imobiliaria
    restart: on-failure
    volumes:
    - .:/app

  fixtures:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python manage.py loaddata empreendimentos.json
    env_file: .env
    image: api_imobiliaria
    depends_on:
    - migrations
    restart: on-failure
    volumes:
    - .:/app
