version: '3.7'

services:

  web:
    container_name: imobiliaria-web
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run gunicorn imobiliaria.wsgi --bind 0.0.0.0:8000
    env_file: .env
    image: api_imobiliaria
    depends_on:
    - postgres
    restart: on-failure
    volumes:
    - .:/app

  caddy:
    image: caddy:2.3.0-alpine
    container_name: caddy
    links:
    - web:web
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python manage.py migrate
    env_file: .env
    image: api_imobiliaria
    depends_on:
    - postgres
    restart: on-failure
    volumes:
    - .:/app

  fixtures:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python manage.py loaddata preco_metro_quadrado.json
    env_file: .env
    image: api_imobiliaria
    depends_on:
    - migrations
    restart: on-failure
    volumes:
    - .:/app
