# Generated by Django 3.2.4 on 2021-06-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('valor_metro_quadrado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'empreendimento',
                'verbose_name_plural': 'empreendimentos',
                'db_table': 'empreendimento',
            },
        ),
    ]
