# Generated by Django 3.2.4 on 2021-06-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteamento',
            old_name='valor',
            new_name='valor_metro_quadrado',
        ),
    ]
