version: '3.7'

services:

  api-consulta:
    container_name: api-consulta
    build:
      context: .
      dockerfile: ../Dockerfile
    command: pipenv run gunicorn settings.wsgi --bind 0:9000
    env_file: .env
    network_mode: host
    image: api-consulta:1.0.0
    restart: on-failure
    volumes:
      - .:/app

  migrations:
    build:
      context: .
      dockerfile: ../Dockerfile
    command: pipenv run python manage.py migrate
    env_file: .env
    image: api-consulta:1.0.0
    restart: on-failure
    volumes:
      - .:/app

  fixtures:
    build:
      context: .
      dockerfile: ../Dockerfile
    command: pipenv run python manage.py loaddata empreendimentos.json
    env_file: .env
    image: api-consulta:1.0.0
    depends_on:
      - migrations
    volumes:
      - .:/app
